[package]
name = "rust_rp_main"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level=3

[dependencies]
rand = "0.9"
lazy_static = "1.5.0"
argh = "0.1.13"

[lints.rust]
unused = "allow"
dead_code = "allow"
