insertion_sort: sorting/insertion_sort.rs
	cargo single build sorting/insertion_sort.rs

quick_sort: sorting/quick_sort.rs
	cargo single build sorting/quick_sort.rs

sorting: insertion_sort quick_sort
all: sorting
